name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
    JFROG_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
    JFROG_PASS: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
    SONATYPE_GPG_KEY_BASE64: ${{ secrets.SONATYPE_GPG_KEY_BASE64 }}
    SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    SONATYPE_GPG_KEY_PASSWORD: ${{ secrets.SONATYPE_GPG_KEY_PASSWORD }}
    NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
jobs:
  maven-package:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy maven settings
        run: |
          wget https://raw.githubusercontent.com/entur/ror-maven-settings/master/.m2/settings.xml -O .github/workflows/settings.xml
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Run maven build
        run: mvn verify -s .github/workflows/settings.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: target/*.jar
  publish-release:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    name: Publish release to maven central
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@v1
    secrets: inherit
    with:
      push_to_repo: true
      snapshot: false